---
title: "Quiz1"
output: html_document
---

### Question 1

The en_US.blogs.txt  file has 200 megabytes.

### Question 2

The en_US.twitter.txt has over 2 million lines of text?

### Question 3 (Wrong)

The longest string in:
- en_US.twitter.txt is 211
- en_US.news.txt is 5,760
- en_US.blogs.txt is 37,241

new numbers:
blogs 40833
news 11384

So:

What is the length of the longest line seen in any of the three en_US data sets? Over 11 thousand in the blogs data set

### Question 4

The word "love" appears in the en_US twitter data set 58,928 times in any case or 45,598 times in lower case only.

In the en_US twitter data set, if you divide the number of lines where the word "love" (all lowercase) occurs by the number of lines the word "hate" (all lowercase) occurs, you get about 4.

### Question 5

The one tweet in the en_US twitter data set that matches the word "biostats" says

"i know how you feel.. i have biostats on tuesday and i have yet to study =/"

In other words "They haven't studied for their biostats exam".

### Question 6 wrong

Only one tweet contains the line "A computer once beat me at chess, but it was no match for me at kickboxing".

There are 9 similar variations.

Due to errors reading in the file I'm not finding all string results. According to notepad++ there are 3 hits.
